makefile/linux: Fix missing linker flag -ldl
The core uses dlopen on linux but didn't specifiy -ldl resulting in
undefined reference errors:

mednafen/snes/src/chip/supergameboy/supergameboy.o: In function `nall::library::close()':
mednafen/snes/src/lib/nall/dl.hpp:57: undefined reference to `dlclose'
mednafen/snes/src/chip/supergameboy/supergameboy.o: In function `nall::library::open(char const*)':
mednafen/snes/src/lib/nall/dl.hpp:39: undefined reference to `dlopen'
mednafen/snes/src/lib/nall/dl.hpp:52: undefined reference to `dlsym'